[project]
name = "radical-stereochemistry-code"
version = "0.1.0"
description = "Add a short description here"
authors = ["Andreas Copan <avcopan@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
python = ">=3.12.1,<3.13"
jupyter = ">=1.0.0,<1.1"
