[project]
name = "radical-stereochemistry-code"
version = "0.1.0"
description = "Add a short description here"
authors = ["Andreas Copan <avcopan@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
python = ">=3.12.1,<3.13"
jupyter = ">=1.0.0,<1.1"
pandas = ">=2.2.0,<2.3"
rdkit = ">=2023.9.4,<2023.10"
pytest = ">=7.4.4,<7.5"
networkx = ">=3.2.1,<3.3"
more-itertools = ">=10.2.0,<10.3"
qcelemental = ">=0.27.1,<0.28"
scipy = ">=1.12.0,<1.13"
py3dmol = ">=2.0.4,<2.1"
xarray = ">=2024.1.1,<2024.2"
ipython = ">=8.20.0,<8.21"
tqdm = ">=4.66.1,<4.67"
mako = ">=1.3.1,<1.4"
pyarrow = ">=14.0.2,<14.1"
